<script type="text/javascript" src="${resourcesUrl}/fas/resources/js/modules/self_shop_bank_info/self_shop_day_report/self_shop_day_report_brand.js?version=${version}"></script>
<div class="easyui-layout" data-options="fit:true">
	<div data-options="region:'center',border:false">
	     <@p.datagrid id="dataGridDivForBrand"  loadUrl="" saveUrl=""   defaultColumn=""
	             isHasToolBar="false"    onClickRowEdit="false"    pagination="true"  checkOnSelect="true" selectOnCheck="true"
	           rownumbers="true" singleSelect="false"  showFooter="true"
	           columnsJsonList="[
						{field : 't',checkbox:true,width : 30,notexport:true,rowspan:'2'},
		                {field : 'id',hidden : 'true',align:'center',notexport:true,rowspan:'2'},
		                {field : 'shopNo',title : '店铺编码',width : 100,align:'left',rowspan:'2'},
						{field : 'shopName',title : '店铺名称',width : 150,align:'left',rowspan:'2'},
						{field : 'companyNo',title : '公司编码',width : 100,align:'left',rowspan:'2'},
						{field : 'companyName',title : '公司名称',width : 150,align:'left',rowspan:'2'},
						{field:'brandNo',title:'品牌部编号',width:80,sortable:true,hidden:true,rowspan:'2'},
						{field:'brandName',title:'品牌名称',width:80,sortable:true,hidden:true,rowspan:'2'},
						{field:'brandUnitName',title:'品牌部名称',width:80,sortable:true,rowspan:'2'},
						{field : 'outDate',title : '销售日期',width : 100,align:'center',rowspan:'2'},
						
						{title:'销售',colspan:'0'},
						{title:'实收',colspan:'0'},
						{title:'差异',colspan:'0'},
						{title:'进账',colspan:'0'}
						],
	               
	            		[{field : 'p01',title : '现金',width : 80,align:'center',exportType:'number',formatter: function(value,row,index){
		                	if(value == undefined){return 0;}else{return value;}
		                }},	
						{field : 'p03',title : '现金券',width : 80,align:'center',exportType:'number'},	
						{field : 'p04',title : '银行卡',width : 80,align:'center',exportType:'number'},
						{field : 'p05',title : '商场卡',width : 80,align:'center',exportType:'number'},
						{field : 'p06',title : '其它',width : 80,align:'center',exportType:'number'},
						{field : 'p08',title : '商场券',width : 80,align:'center',exportType:'number'},
						{field : 'p09',title : '预付款',width : 80,align:'center',exportType:'number'},
						{field : 'p10',title : '支票',width : 80,align:'center',exportType:'number'},
						{field : 'p11',title : '减现额/接劵额',width : 120,align:'center',exportType:'number'},
						{field : 'p12',title : '国外银行卡',width : 90,align:'center',exportType:'number'},
						{field : 'p13',title : 'IC卡',width : 80,align:'center',exportType:'number'},
						{field : 'p14',title : '公司折扣券',width : 90,align:'center',exportType:'number'},
						{field : 'p15',title : '商场折扣券',width : 90,align:'center',exportType:'number'},
						{field : 'p16',title : '美元',width : 80,align:'center',exportType:'number'},
						{field : 'p17',title : '港币',width : 80,align:'center',exportType:'number'},
						{field : 'p18',title : '联华卡',width : 80,align:'center',exportType:'number'},
						{field : 'p19',title : '市民卡',width : 80,align:'center',exportType:'number'},
						{field : 'p20',title : '商盟卡',width : 80,align:'center',exportType:'number'},
						{field : 'p20151010',title : '支付宝(商场收银)',width : 120,align:'center',exportType:'number'},
						{field : 'p21',title : '支付宝(当面付)',width : 120,align:'center',exportType:'number'},
						{field : 'p22',title : '微信(当面付)',width : 120,align:'center',exportType:'number'},
						{field : 'p23',title : '储值卡',width : 80,align:'center',exportType:'number'},
						{field : 'p24',title : '其它外卡',width : 80,align:'center',exportType:'number'},
						{field : 'p25',title : '商场现金劵',width : 100,align:'center',exportType:'number'},
						{field : 'p26',title : '心赏卡',width : 80,align:'center',exportType:'number'},
						{field : 'p27',title : '商场会员卡',width : 100,align:'center',exportType:'number'},
						{field : 'p28',title : '提货券',width : 80,align:'center',exportType:'number'},
						{field : 'p29',title : '外币卡',width : 80,align:'center',exportType:'number'},
						{field : 'p30',title : '刷卡退款',width : 80,align:'center',exportType:'number'},
						{field : 'p31',title : '商场储值卡',width : 100,align:'center',exportType:'number'},
						{field : 'p32',title : '百丽储值卡',width : 100,align:'center',exportType:'number'},
						{field : 'p33',title : '支付宝',width : 80,align:'center',exportType:'number'},
						{field : 'p35',title : '储值购物卡',width : 100,align:'center',exportType:'number'},
						{field : 'p36',title : '微信(商场收银)',width : 120,align:'center',exportType:'number'},
						{field : 'p37',title : '支付宝(第三方)',width : 120,align:'center',exportType:'number'},
						{field : 'p38',title : '微信支付(第三方)',width : 120,align:'center',exportType:'number'},
						{field : 'p999',title : '支付宝当面付',width : 120,align:'center',exportType:'number'},
						{field : 'totalAmount',title : '销售合计',width : 80,align:'center',exportType:'number'},
						
						{field : 's01',title : '现金',width : 80,align:'center',exportType:'number'},	
						{field : 's03',title : '现金券',width : 80,align:'center',exportType:'number'},	
						{field : 's04',title : '银行卡',width : 80,align:'center',exportType:'number'},
						{field : 's05',title : '商场卡',width : 80,align:'center',exportType:'number'},
						{field : 's06',title : '其它',width : 80,align:'center',exportType:'number'},
						{field : 's08',title : '商场券',width : 80,align:'center',exportType:'number'},
						{field : 's09',title : '预付款',width : 80,align:'center',exportType:'number'},
						{field : 's10',title : '支票',width : 80,align:'center',exportType:'number'},
						{field : 's11',title : '减现额接劵额',width : 120,align:'center',exportType:'number'},
						{field : 's12',title : '国外银行卡',width : 90,align:'center',exportType:'number'},
						{field : 's13',title : 'IC卡',width : 80,align:'center',exportType:'number'},
						{field : 's14',title : '公司折扣券',width : 90,align:'center',exportType:'number'},
						{field : 's15',title : '商场折扣券',width : 90,align:'center',exportType:'number'},
						{field : 's16',title : '美元',width : 80,align:'center',exportType:'number'},
						{field : 's17',title : '港币',width : 80,align:'center',exportType:'number'},
						{field : 's18',title : '联华卡',width : 80,align:'center',exportType:'number'},
						{field : 's19',title : '市民卡',width : 80,align:'center',exportType:'number'},
						{field : 's20',title : '商盟卡',width : 80,align:'center',exportType:'number'},
						{field : 's20151010',title : '支付宝(商场收银)',width : 120,align:'center',exportType:'number'},
						{field : 's21',title : '支付宝',width : 80,align:'center',exportType:'number'},
						{field : 's22',title : '微信支付',width : 80,align:'center',exportType:'number'},
						{field : 's23',title : '储值卡',width : 80,align:'center',exportType:'number'},
						{field : 's24',title : '其它外卡',width : 80,align:'center',exportType:'number'},
						{field : 's25',title : '商场现金劵',width : 100,align:'center',exportType:'number'},
						{field : 's26',title : '心赏卡',width : 80,align:'center',exportType:'number'},
						{field : 's27',title : '商场会员卡',width : 100,align:'center',exportType:'number'},
						{field : 's28',title : '提货券',width : 80,align:'center',exportType:'number'},
						{field : 's29',title : '外币卡',width : 80,align:'center',exportType:'number'},
						{field : 's30',title : '刷卡退款',width : 80,align:'center',exportType:'number'},
						{field : 's31',title : '商场储值卡',width : 100,align:'center',exportType:'number'},
						{field : 's32',title : '百丽储值卡',width : 100,align:'center',exportType:'number'},
						{field : 's33',title : '支付宝',width : 80,align:'center',exportType:'number'},
						{field : 's35',title : '储值购物卡',width : 100,align:'center',exportType:'number'},
						{field : 's36',title : '微信(商场收银)',width : 120,align:'center',exportType:'number'},
						{field : 's37',title : '支付宝(第三方)',width : 120,align:'center',exportType:'number'},
						{field : 's38',title : '微信支付(第三方)',width : 120,align:'center',exportType:'number'},
						{field : 's999',title : '支付宝当面付',width : 120,align:'center',exportType:'number'},
						{field : 'amount',title : '实收合计',width : 80,align:'center',exportType:'number'},
						
						{field : 'd01',title : '现金',width : 80,align:'center',exportType:'number'},	
						{field : 'd03',title : '现金券',width : 80,align:'center',exportType:'number'},	
						{field : 'd04',title : '银行卡',width : 80,align:'center',exportType:'number'},
						{field : 'd05',title : '商场卡',width : 80,align:'center',exportType:'number'},
						{field : 'd06',title : '其它',width : 80,align:'center',exportType:'number'},
						{field : 'd08',title : '商场券',width : 80,align:'center',exportType:'number'},
						{field : 'd09',title : '预付款',width : 80,align:'center',exportType:'number'},
						{field : 'd10',title : '支票',width : 80,align:'center',exportType:'number'},
						{field : 'd11',title : '减现额接劵额',width : 120,align:'center',exportType:'number'},
						{field : 'd12',title : '国外银行卡',width : 90,align:'center',exportType:'number'},
						{field : 'd13',title : 'IC卡',width : 80,align:'center',exportType:'number'},
						{field : 'd14',title : '公司折扣券',width : 90,align:'center',exportType:'number'},
						{field : 'd15',title : '商场折扣券',width : 90,align:'center',exportType:'number'},
						{field : 'd16',title : '美元',width : 80,align:'center',exportType:'number'},
						{field : 'd17',title : '港币',width : 80,align:'center',exportType:'number'},
						{field : 'd18',title : '联华卡',width : 80,align:'center',exportType:'number'},
						{field : 'd19',title : '市民卡',width : 80,align:'center',exportType:'number'},
						{field : 'd20',title : '商盟卡',width : 80,align:'center',exportType:'number'},
						{field : 'd20151010',title : '支付宝(商场收银)',width : 120,align:'center',exportType:'number'},
						{field : 'd21',title : '支付宝',width : 80,align:'center',exportType:'number'},
						{field : 'd22',title : '微信支付',width : 80,align:'center',exportType:'number'},
						{field : 'd23',title : '储值卡',width : 80,align:'center',exportType:'number'},
						{field : 'd24',title : '其它外卡',width : 80,align:'center',exportType:'number'},
						{field : 'd25',title : '商场现金劵',width : 90,align:'center',exportType:'number'},
						{field : 'd26',title : '心赏卡',width : 80,align:'center',exportType:'number'},
						{field : 'd27',title : '商场会员卡',width : 90,align:'center',exportType:'number'},
						{field : 'd28',title : '提货券',width : 80,align:'center',exportType:'number'},
						{field : 'd29',title : '外币卡',width : 80,align:'center',exportType:'number'},
						{field : 'd30',title : '刷卡退款',width : 80,align:'center',exportType:'number'},
						{field : 'd31',title : '商场储值卡',width : 90,align:'center',exportType:'number'},
						{field : 'd32',title : '百丽储值卡',width : 90,align:'center',exportType:'number'},
						{field : 'd33',title : '支付宝',width : 80,align:'center',exportType:'number'},
						{field : 'd35',title : '储值购物卡',width : 80,align:'center',exportType:'number'},
						{field : 'd36',title : '微信(商场收银)',width : 120,align:'center',exportType:'number'},
						{field : 'd37',title : '支付宝(第三方)',width : 120,align:'center',exportType:'number'},
						{field : 'd38',title : '微信支付(第三方)',width : 120,align:'center',exportType:'number'},
						{field : 'd999',title : '支付宝当面付',width : 120,align:'center',exportType:'number'},
						{field : 'returnAmount',title : '银行卡系统退款',width : 120,align:'center',exportType:'number'},
						{field : 'actualReturnAmount',title : '银行卡实际退款',width : 120,align:'center',exportType:'number'},
						{field : 'diffAmount',title : '差异合计',width : 80,align:'center',exportType:'number'},
						
						{field : 'poundage',title : '手续费',width : 80,align:'center',exportType:'number'},
						{field : 'sum',title : '进账合计',width : 80,align:'center',exportType:'number'}
				        ]" 
		          jsonExtend='{}'
	              />
	</div>
</div>